version: "2.0"
services:
  xion-relay:
    image: xion/relay:pre-genesis-placeholder
    expose:
      - port: 8443
        as: 443
        to:
          - global: true
    env:
      - XION_API_HOST=0.0.0.0
      - XION_API_PORT=8443
      - XION_API_WORKERS=1
profiles:
  compute:
    xion-relay:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 10Gi
  placement:
    dcloud:
      pricing:
        xion-relay:
          denom: uakt
          amount: 1000
deployment:
  xion-relay:
    dcloud:
      profile: xion-relay
      count: 1
