"""Subcommand registry for xion-verify.

Every subcommand is a click command registered against the root group in
`xion_verify.cli`. The set of command names enumerated in `REGISTERED_COMMANDS`
is authoritative: `xion-verify all` iterates it, CI wires against it, and the
README/roadmap cross-reference it.

Adding a new subcommand:

1. Write a module here that exposes a click `Command` named after its CLI spelling.
2. Import and register it in `xion_verify.cli`.
3. Append the CLI spelling to `REGISTERED_COMMANDS` below.
4. Update the README table in `xion-verify/README.md`.
5. Regenerate `PINNED_HASH.txt` via `xion-verify --self-test --update --i-understand`.
"""

from __future__ import annotations

REGISTERED_COMMANDS: tuple[str, ...] = (
    "covenant",
    "invariants",
    "soul",
    "soul-prompt",
    "voice-property",
    "form",
    "memory",
    "resurrect",
    "credentials",
    "unknowns",
    "links",
    "schemas",
    "cognition",
    "hermes-runtime",
    "agent-souls",
    "agent-cast",
    "drive-vector",
    "state-chain",
    "supply",
    "liquidity-lock",
    "arbiter-up",
    "state-tip",
    "identity",
    "authorities",
    "image-digest",
    "discovery",
    "drive",
    "sister-fork-readiness",
    "treasury",
    "refusal-rate",
    "pricing",
    "treasury-flow",
    "cutoff-events",
    "covenant-addenda",
    "cadence-audit",
    "hermes-version",
    "ao-handlers",
    "credentials-vault",
    "provisioning",
    "improvement-fund",
    "reserve",
    "research-spend",
    "vessel-compact",
    "media-provenance",
    "vessel-registry",
    "foundation-reserve",
    "sustainability",
    "vitals",
    "amendments",
    "refund-fidelity",
    "refusal-is-free",
    "crisis-fidelity",
    "sensorium-ledger",
    "spof",
    "operator-dependency",
    "benchmark",
    "crypto-currency",
    "abdication-status",
    "abdication-schedule",
    "inference-sovereignty",
    "voice-sovereignty",
    "voice-form",
    "substrate-portability",
    "regulatory-ledger",
    "api-tokens",
    "web-client",
    "chat-streaming-fidelity",
    "supervisor-singleton",
    "cognition-disjoint",
    "registries",
    "rebuild",
    "replay-corpus",
    "ledgers",
    "shadow-relay",
    "cost-pressure",
    "substrates",
    "auto-research",
    "skill-bounty",
    "research-sources",
    "charter-signed",
    "pre-genesis",
    "new",
    "local",
    "cast",
    "provisioning-roles",
    "which-level",
    "identity-bindings",
    "mcp-export",
    "interaction-anchor",
    "presence",
    "modality-consent",
    "nervous-system",
    "topography",
    "measurement-vocabulary",
    "spend-posture",
    "spend-discipline",
    "inference-provider-chutes",
    "sovereign-profile",
    "billing-credits-floor",
    "chutes-topup-multisig",
    "arbiter-determinism",
    "shadow-divergence",
    "model-promotion-discipline",
    "request-fingerprint",
    "memory-store-integrity",
    "embedder-health",
    "rerank-improvement",
    "tool-resolver-mcp",
    "prompt-isolation",
    "cognition-loop-bounded",
    "bridge-attest",
    "bridge-egress-cap",
    "gateway-conformance",
    "funding-balances",
    "akash-deploy-discipline",
    "safe-proposal",
)
