#!/usr/bin/env bash
# Seed ArLocal for permaweb/ao-localnet (module + scheduler + mine).
#
# The upstream stack does not spawn processes until the mock chain has the
# published Module and Scheduler-Location txs (see upstream README "Seed data
# onto the blockchain"). Without this, `aos` often fails with:
#   Invalid Return 'undefined': Required
#
# Prereq: `bash scripts/ao-localnet-up.sh` has already started Docker; port 4000
# (ArLocal) is up. Run this from the same WSL/shell. Needs: curl, node, sh.
#
# Usage:
#   bash scripts/ao-localnet-seed.sh
#
# After success, run `bash scripts/ao-localnet-seal.sh` (or `aos` per runbook).

set -euo pipefail

script_dir() {
  local src="${BASH_SOURCE[0]}"
  while [ -h "$src" ]; do
    local dir
    dir="$(cd -P "$(dirname "$src")" && pwd)"
    src="$(readlink "$src")"
    [[ "$src" != /* ]] && src="$dir/$src"
  done
  cd -P "$(dirname "$src")" && pwd
}
SCRIPT_DIR="$(script_dir)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SEED_DIR="$REPO_ROOT/infra/ao-localnet/.upstream/seed"

log()  { printf '[ao-localnet-seed] %s\n' "$*" >&2; }
fail() { printf '[ao-localnet-seed] FAIL: %s\n' "$*" >&2; exit 1; }

[ -d "$SEED_DIR" ] || fail "missing $SEED_DIR — run scripts/ao-localnet-up.sh first to clone .upstream"
if [ -f "$HOME/.nvm/nvm.sh" ]; then
  # shellcheck source=/dev/null
  . "$HOME/.nvm/nvm.sh"
  nvm use 20 2>/dev/null || nvm use node 2>/dev/null || true
fi
command -v curl >/dev/null 2>&1 || fail "curl not in PATH"
command -v node >/dev/null 2>&1 || fail "node not in PATH (install nvm + Node 20, or add node to PATH)"

curl -sS -m 2 "http://localhost:4000/info" >/dev/null 2>&1 || fail "ArLocal not reachable at http://localhost:4000 — start: bash scripts/ao-localnet-up.sh"

log "downloading AOS module WASM (extras/aos.wasm) …"
mkdir -p "$SEED_DIR/extras"
( cd "$SEED_DIR" && sh ./download-aos-module.sh )

# Upstream sets Scheduler-Location Url to http://host.docker.internal:4003.
# The messenger (`mu` container) must be able to open that URL; on Linux /
# WSL, `host.docker.internal` is often missing and the MU then throws
# 500: Cannot destructure property 'url' of 'undefined' when resolving
# the scheduler. Use the Compose service name on the Docker network instead.
xion_patch_scheduler_su_url() {
  local pub="$SEED_DIR/publish-scheduler-location.mjs"
  [ -f "$pub" ] || return 0
  local su="${XION_LOCALNET_SU_URL:-http://su:80}"
  if ! grep -qF 'host.docker.internal' "$pub" 2>/dev/null; then
    log "scheduler seed script already patched (no host.docker.internal) — ok"
    return 0
  fi
  log "patching $pub: Scheduler-Location Url -> $su (set XION_LOCALNET_SU_URL to override)"
  cp -a "$pub" "$pub.bak.xion" 2>/dev/null || true
  if sed --version 2>&1 | grep -q GNU; then
    sed -i "s#http://host.docker.internal:4003#${su}#g" "$pub"
  else
    sed -i '' "s#http://host.docker.internal:4003#${su}#g" "$pub"
  fi
}
xion_patch_scheduler_su_url

log "publishing scheduler location + AOS module + mining blocks (upstream seed/seed-for-aos.sh) …"
SEED_LOG="$(mktemp)"
( cd "$SEED_DIR" && sh ./seed-for-aos.sh ) 2>&1 | tee "$SEED_LOG"
# `aos` defaults to a *public* module id from @permaweb/aos package.json; local spawn
# must use the module tx id just published to ArLocal, or aoconnect returns
# "Invalid Return 'undefined'".
#
# `aos` spawn also tags the process with `process.env.SCHEDULER` (see
# @permaweb/aos `src/services/connect.js`), defaulting to mainnet. The MU must
# have a Scheduler-Location for that Arweave address or it returns
# 500: Cannot destructure property 'url' of 'undefined'. The seed publishes
# Scheduler-Location from `scheduler-location-publisher-wallet.json`; export
# that address as `SCHEDULER` (same string printed by publish-scheduler-location.mjs).
MODLINE="$(grep 'aos module:' "$SEED_LOG" | tail -1 || true)"
SCHLINE="$(grep 'scheduler location publisher address:' "$SEED_LOG" | tail -1 || true)"
rm -f "$SEED_LOG"
AOS_MOD=""
if [ -n "$MODLINE" ]; then
  AOS_MOD="${MODLINE#*aos module:}"
  AOS_MOD="$(printf '%s' "$AOS_MOD" | tr -d ' \r' | tr -d '\n')"
fi
SCHED_ADDR=""
if [ -n "$SCHLINE" ]; then
  SCHED_ADDR="${SCHLINE#*scheduler location publisher address:}"
  SCHED_ADDR="$(printf '%s' "$SCHED_ADDR" | tr -d ' \r' | tr -d '\n')"
fi
if [ -n "$AOS_MOD" ] || [ -n "$SCHED_ADDR" ]; then
  {
    echo "# Generated by ao-localnet-seed.sh — source before aos (local module + scheduler on ArLocal)."
    [ -n "$AOS_MOD" ] && echo "export AOS_MODULE=\"$AOS_MOD\""
    [ -n "$SCHED_ADDR" ] && echo "export SCHEDULER=\"$SCH_ADDR\""
    # aos 2.0: without this string, connect() uses mainnet readResult; local CU never sees the process.
    echo "export AO_URL=\"undefined\""
  } > "$REPO_ROOT/infra/ao-localnet/localnet-aos.env"
  log "wrote $REPO_ROOT/infra/ao-localnet/localnet-aos.env (AOS_MODULE=${AOS_MOD:-<missing>}, SCHEDULER=${SCHED_ADDR:-<missing>})"
else
  log "warn: could not parse 'aos module:' or scheduler line from seed log; set AOS_MODULE and SCHEDULER manually"
fi
[ -n "$AOS_MOD" ] || log "warn: no AOS_MODULE in env file — set from seed 'aos module:' line"
[ -n "$SCHED_ADDR" ] || log "warn: no SCHEDULER in env file — set to scheduler location publisher address or spawn will use mainnet default and MU may 500"

# Fund wallets on ArLocal. The localnet bundler posts process/module txs to ArLocal; if its wallet has
# no AR, you get HTTP 410 from ArLocal, bundler never persists the process, and the CU returns
# "Process … was not found on gateway" / aos: "Could not connect to process".
# Upstream: infra/ao-localnet/.upstream/wallets/bundler-wallet.json.
_GNPM="$(npm root -g 2>/dev/null || true)"
# npm global root may be empty in some PATH setups; nvm + global @permaweb/aos
# is typically next to the node binary.
if [ -z "$_GNPM" ] && [ -n "$(command -v node 2>/dev/null)" ]; then
  _ND="$(dirname "$(command -v node)")"
  for _cand in "$_ND/../lib/node_modules" "$_ND/../../lib/node_modules"; do
    if [ -d "$_cand/@permaweb/aos/node_modules" ]; then
      _GNPM="$_cand"
      break
    fi
  done
fi
BUNDLER_JWK="$REPO_ROOT/infra/ao-localnet/.upstream/wallets/bundler-wallet.json"
if [ -n "$_GNPM" ]; then
  export NODE_PATH="${_GNPM}/@permaweb/aos/node_modules:${_GNPM}:${NODE_PATH:-}"
  if [ -f "$BUNDLER_JWK" ]; then
    if node "$REPO_ROOT/scripts/ao_arlocal_mint_aos.cjs" "$BUNDLER_JWK" 2>&1; then
      log "ArLocal bundler wallet funded (so spawn txs can be posted on-chain; see bundler logs if still 410)"
    else
      log "warn: could not mint to bundler wallet — spawns may fail with process not on gateway"
    fi
  fi
  if [ -f "$HOME/.aos.json" ]; then
    if node "$REPO_ROOT/scripts/ao_arlocal_mint_aos.cjs" 2>&1; then
      log "ArLocal operator wallet minted + block mined (see ao_arlocal_mint_aos.cjs)"
    else
      log "warn: could not run ao_arlocal_mint_aos.cjs (non-fatal if your aos wallet already has AR)"
    fi
  else
    log "no ~/.aos.json — run \`aos\` once to create a wallet, then re-run this script to mint the operator, or use manual ArLocal /mint/ (runbook)"
  fi
else
  log "warn: could not resolve @permaweb/aos on NODE_PATH (install: npm i -g https://get_ao.arweave.net) — skipping auto-mint; use manual /mint/ for bundler + operator if spawn fails"
fi

log "OK. Source env then seal:"
log "  set -a && . $REPO_ROOT/infra/ao-localnet/localnet-aos.env && set +a   # or: new shell after 'source …'"
log "  bash $SCRIPT_DIR/ao-localnet-seal.sh"
log "  (or follow docs/runbooks/AO_DEPLOY_LOCALNET.md for interactive aos)"
